### ISSUE TITLE
Send out data notice for migration

### ISSUE THREAD

**Issue by mindofmar** [wallet-guard/wallet-guard-extension#166]
# TODOS
- [x] Update walletguard website, chrome web store (and all applications) to link to Consensys [terms of use](https://consensys.io/terms-of-use) and [privacy notice](https://consensys.io/privacy-notice). Direct linking is what we want, not creating a new page.

Some combination of the following to let users know:
- [x] Send email to our email list letting them know we've been acquired
- [ ] Send Discord announcement to users letting them know we've been acquired
- [x] Extension release: Create an in-app banner that "provides a clear link to the Consensys global privacy notice." AND/OR Create an in-app banner in the Dashboard (whichever one the user sees first)

We've signed off on the [following copy](https://docs.google.com/document/d/1Mo9QL6sTQVpKMcTIcGrgFotcfM8nWV0_vZbfAL0OJ1A/edit)
